version: '3'
services:
  backend:
    image: alexm21/backend_ayd2:1.2.0
    ports:
      - "9000:9000"  # Mapea el puerto 9000 del host al contenedor
      - "9001:9001"  # Mapea el puerto 9001 del host al contenedor
    env_file:
      - ./Backend/.env  # Ruta al archivo .env en el backend
    networks:
      - app-network

  frontend:
    image: alexm21/frontend_ayd2:1.2.0
    ports:
      - "3000:3000"  # Mapea el puerto 3000 del host al contenedor
    networks:
      - app-network
    depends_on:
      - backend  # Asegura que el backend esté activo antes de iniciar el frontend


networks:
  app-network:
    driver: bridge