# Usa la imagen oficial de Node.js como base
FROM node:18

# Establece el directorio de trabajo
WORKDIR /usr/src/app

# Copia los archivos de configuración de la aplicación
COPY package*.json ./
COPY .env ./

# Instala las dependencias
RUN npm install

# Copia el resto de los archivos de la aplicación
COPY . .

# Expone el puerto que tu aplicación utiliza (ajusta según sea necesario)
EXPOSE 9000 9001

# Comando para iniciar la aplicación
CMD ["node", "server.js"]  